name: Daily Rain Alert

on:
  schedule:
    # 9:10 AM IST is 3:40 AM UTC
    - cron: '35 10 * * *'
  workflow_dispatch: # This allows you to still run it manually for testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests twilio

      - name: Run script
        env:
          OWM_API_KEY: ${{ secrets.OWM_API_KEY }}
          ACCOUNT_SID: ${{ secrets.ACCOUNT_SID }}
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          FROM: ${{ secrets.FROM }}
          NUMBERS: ${{ secrets.NUMBERS }}
        run: python main.py
